name: Format code on every PR

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

     - name: autopep8
       uses: peter-evans/autopep8@v1.2.1

